packages:
  - "apps/api"
  - "apps/web"
  - "packages/core/*"
  - "packages/clients/*"
  - "packages/testing/*"
  - "packages/ui"
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  msw: false
  protobufjs: true
  sharp: true
